CREATE TABLE `drones` (
                          `id` BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          `serial_number` varchar(100) NOT NULL,
                          `model` varchar(20) NOT NULL,
                          `weight_limit` DECIMAL(6 , 3) NOT NULL,
                          `battery_capacity` INT(3) NOT NULL,
                          `state` varchar(20) NOT NULL
);

CREATE TABLE `medications` (
                            id BIGINT PRIMARY KEY AUTO_INCREMENT,
                            name VARCHAR(200),
                            weight DECIMAL(10,2),
                            code VARCHAR(100),
                            image BLOB
);
